{
 "title": "Compare Hardware Capturings",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Test_Id",
    "label": "Test Result Ids",
    "query": "SELECT Id\nFROM NetworkPerformanceTest.LatencyTestResults"
   }
  ]
 },
 "panels": [
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 24, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  LatencyTestParameters.LatencyTestResultId as \"Test Id\",\n  TransmissionTechnology as \"Transmission Technology\",\n  TestTool as \"Tool\",\n  TestMode as \"Mode\",\n  Protocol,\n  MessageSize as \"Message Size\",\n  MessagesPerSecond as \"Message Rate\",\n  TestDuration as \"Test Duration\",\n  COUNT(CASE WHEN LatencyTestMeasurments.CapturedOneWayLatencyClientToServer > 0 THEN 1 END) AS \"Ping-Pings\",\n  COUNT(CASE WHEN LatencyTestMeasurments.CapturedProcessingTimeServer > 0 THEN 1 END) AS \"Processing Times\",\n  COUNT(CASE WHEN LatencyTestMeasurments.CapturedOneWayLatencyServerToClient > 0 THEN 1 END) AS \"Pong-Pongs\",\n  COUNT(CASE WHEN LatencyTestMeasurments.CapturedLatency > 0 THEN 1 END) AS \"Ping-Pongs\",\n  LatencyTestResults.ReceivedMessages AS \"Received Packets\"\nFROM LatencyTestResults, LatencyTestParameters, LatencyTestMeasurments\nWHERE LatencyTestParameters.LatencyTestResultId IN (${Test_Id:singlequote})\nAND LatencyTestParameters.LatencyTestResultId = LatencyTestMeasurments.LatencyTestResultId AND LatencyTestResults.Id = LatencyTestParameters.LatencyTestResultId\nGROUP BY LatencyTestParameters.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "One Way Latency | Client ---> Server",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  StartTimestamp AS \"time\",\n  Id\nFROM ThroughputTestParameters\nWHERE\n  $__timeFilter(StartTimestamp)\nORDER BY StartTimestamp"
    }
   ]
  },
  {
   "title": "Average",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  AVG(LatencyTestMeasurments.CapturedOneWayLatencyClientToServer) AS \"Average\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.CapturedOneWayLatencyClientToServer > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  MAX(LatencyTestMeasurments.CapturedOneWayLatencyClientToServer) AS \"Maximum\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.CapturedOneWayLatencyClientToServer > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "One Way Latency | Server ---> Client",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT\n  StartTimestamp AS \"time\",\n  Id\nFROM ThroughputTestParameters\nWHERE\n  $__timeFilter(StartTimestamp)\nORDER BY StartTimestamp"
    }
   ]
  },
  {
   "title": "Average",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  AVG(LatencyTestMeasurments.CapturedOneWayLatencyServerToClient) AS \"Average\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.CapturedOneWayLatencyServerToClient > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  MAX(LatencyTestMeasurments.CapturedOneWayLatencyServerToClient) AS \"Maximum\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.CapturedOneWayLatencyServerToClient > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "Processing Time Server",
   "type": "text",
   "gridPos": { "h": 1, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT\n  StartTimestamp AS \"time\",\n  Id\nFROM ThroughputTestParameters\nWHERE\n  $__timeFilter(StartTimestamp)\nORDER BY StartTimestamp"
    }
   ]
  },
  {
   "title": "Average",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  AVG(LatencyTestMeasurments.CapturedProcessingTimeServer) AS \"Average\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.CapturedProcessingTimeServer > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  MAX(LatencyTestMeasurments.CapturedProcessingTimeServer) AS \"Maximum\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.CapturedProcessingTimeServer > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "Latency (Average)",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  StartTimestamp AS \"time\",\n  Id\nFROM ThroughputTestParameters\nWHERE\n  $__timeFilter(StartTimestamp)\nORDER BY StartTimestamp"
    }
   ]
  },
  {
   "title": "Latency (Maximum)",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT\n  StartTimestamp AS \"time\",\n  Id\nFROM ThroughputTestParameters\nWHERE\n  $__timeFilter(StartTimestamp)\nORDER BY StartTimestamp"
    }
   ]
  },
  {
   "title": "Software",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  AVG(LatencyTestMeasurments.Latency) AS \"Latency\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.Latency > 0 AND LatencyTestMeasurments.CapturedLatency > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "Captured",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  AVG(CapturedLatency) AS \"Captured Latency\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.Latency > 0 AND LatencyTestMeasurments.CapturedLatency > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  AVG(LatencyTestMeasurments.Latency-LatencyTestMeasurments.CapturedLatency) AS \"Difference\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.Latency > 0 AND LatencyTestMeasurments.CapturedLatency > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "Software",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  MAX(LatencyTestMeasurments.Latency) AS \"Latency\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.Latency > 0 AND LatencyTestMeasurments.CapturedLatency > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "Captured",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  MAX(CapturedOneWayLatencyServerToClient+CapturedOneWayLatencyClientToServer+CapturedProcessingTimeServer)/2 AS \"Captured Latency\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.Latency > 0 AND LatencyTestMeasurments.CapturedLatency > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.LatencyTestResultId as \"time\",\r\n  MAX(LatencyTestMeasurments.Latency)-MAX(LatencyTestMeasurments.CapturedLatency) AS \"Difference\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId IN (${Test_Id:singlequote})\r\nAND LatencyTestMeasurments.Latency > 0 AND LatencyTestMeasurments.CapturedLatency > 0\r\nGROUP BY LatencyTestMeasurments.LatencyTestResultId"
    }
   ]
  }
 ]
}