{
 "title": "Detailed Hardware Capturing",
 "time": { "from": "1970-01-01T00:00:00.062Z", "to": "1970-01-01T00:00:51.373Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "mysql" },
   {
    "name": "Test_Id",
    "label": "Test Result Id",
    "query": "SELECT Id\nFROM NetworkPerformanceTest.LatencyTestResults"
   }
  ]
 },
 "panels": [
  {
   "title": "Test Details",
   "type": "text",
   "gridPos": { "h": 1, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Message Statistics",
   "type": "text",
   "gridPos": { "h": 1, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Id",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Id\nFROM LatencyTestResults  \nWHERE LatencyTestResults.Id = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Technology",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.TransmissionTechnology\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.Protocol\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Test Tool",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.TestTool\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Test Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.TestMode\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Test Duration [s]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.TestDuration\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Target Host",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.TestServer\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  LatencyTestParameters.MessagesPerSecond\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Message Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  LatencyTestParameters.MessageSize\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Sent Messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SentMessages\nFROM LatencyTestResults \nWHERE LatencyTestResults.Id = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Received Messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ReceivedMessages\nFROM LatencyTestResults \nWHERE LatencyTestResults.Id = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Lost Messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  LostMessages\nFROM LatencyTestResults \nWHERE LatencyTestResults.Id = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Latency Parts",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.Index AS \"time\", \r\n  LatencyTestMeasurments.CapturedProcessingTimeServer AS \"Processing Time Server\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = ${Test_Id:singlequote}\r\nAND LatencyTestMeasurments.CapturedProcessingTimeServer <> -1\r\nAND LatencyTestMeasurments.Index < ${__to:date:ms}"
    },
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.Index AS \"time\", \r\n  LatencyTestMeasurments.CapturedOneWayLatencyClientToServer AS \"One Way Latency - Client to Server\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = ${Test_Id:singlequote}\r\nAND LatencyTestMeasurments.CapturedOneWayLatencyClientToServer <> -1\r\nAND LatencyTestMeasurments.Index < ${__to:date:ms}"
    },
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.Index AS \"time\", \r\n  LatencyTestMeasurments.CapturedOneWayLatencyServerToClient AS \"One Way Latency - Server to Client\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = ${Test_Id:singlequote}\r\nAND LatencyTestMeasurments.CapturedOneWayLatencyServerToClient <> -1\r\nAND LatencyTestMeasurments.Index < ${__to:date:ms}"
    },
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.Index AS \"time\", \r\n  LatencyTestMeasurments.CapturedLatency AS \"Latency - Captured\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = ${Test_Id:singlequote}\r\nAND CapturedLatency <> -1\r\nAND LatencyTestMeasurments.Index < ${__to:date:ms}"
    },
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.Index AS \"time\", \r\n  LatencyTestMeasurments.Latency AS \"Latency - Software\",\r\n  LatencyTestMeasurments.CapturedTapPingClientSide AS \"Ping - Client Side\",\r\n  LatencyTestMeasurments.CapturedTapPingServerSide AS \"Ping - Server Side\",\r\n  LatencyTestMeasurments.CapturedTapPongServerSide AS \"Pong - Server Side\",\r\n  LatencyTestMeasurments.CapturedTapPongClientSide AS \"Pong - Client Side\"\r\nFROM LatencyTestMeasurments  \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = ${Test_Id:singlequote}\r\nAND LatencyTestMeasurments.Index < ${__to:date:ms}"
    }
   ]
  },
  {
   "title": "Captured Ping Pongs",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Latency Parts (%)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    { "panelId": 13 }
   ]
  }
 ]
}