{
 "title": "Latency Test Result",
 "time": { "from": "1969-12-31T23:59:59.972Z", "to": "1970-01-01T00:00:01.017Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "mysql" },
   {
    "name": "Test_Id",
    "label": "Test Result Id",
    "query": "SELECT Id\nFROM NetworkPerformanceTest.LatencyTestResults"
   }
  ]
 },
 "panels": [
  {
   "title": "Test Details",
   "type": "text",
   "gridPos": { "h": 1, "w": 14, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Message Statistics",
   "type": "text",
   "gridPos": { "h": 1, "w": 10, "x": 14, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Id",
   "type": "stat",
   "gridPos": { "h": 2, "w": 1, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  Id\nFROM LatencyTestResults  \nWHERE LatencyTestResults.Id = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Technology",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 1, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.TransmissionTechnology\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Protocol",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.Protocol\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Test Tool",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.TestTool\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Test Mode",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.TestMode\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Test Duration [s]",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 10, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.TestDuration\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Target Host",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.TestServer\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Message Rate",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "msg/s" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  LatencyTestParameters.MessagesPerSecond\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Message Size",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  LatencyTestParameters.MessageSize\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Sent Messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  SentMessages\nFROM LatencyTestResults \nWHERE LatencyTestResults.Id = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Received Messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 20, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  ReceivedMessages\nFROM LatencyTestResults \nWHERE LatencyTestResults.Id = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Lost Messages",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 22, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  LostMessages\nFROM LatencyTestResults \nWHERE LatencyTestResults.Id = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Comment",
   "type": "stat",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestParameters.Comment\r\nFROM LatencyTestParameters  \r\nWHERE LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Minimum",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MinimumLatency AS \"Latency - Minimum\",\n  AverageLatency AS \"Latency - Average\",\n  MaximumLatency AS \"Latency - Maximum\",\n  StandardDeviationLatency AS \"Latency - Standard Deviation\",\n  MinimumJitter AS \"Jitter - Minimum\",\n  AverageJitter AS \"Jitter - Average\",\n  MaximumJitter AS \"Jitter - Maximum\",\n  StandardDeviationJitter AS \"Jitter - Standard Deviation\"\nFROM LatencyTestResults \nWHERE LatencyTestResults.Id = ${Test_Id:singlequote}"
    }
   ]
  },
  {
   "title": "Average",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Maximum",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Standard Deviation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Minimum",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Average",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Maximum",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Standard Deviation",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "min" ] } },
   "targets": [
    { "panelId": 9 }
   ]
  },
  {
   "title": "Latency Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.Index AS \"time\", \r\n  LatencyTestMeasurments.Latency AS \"Latency - Software Measurment\",\r\n  LatencyTestMeasurments.Jitter AS \"Jitter - Software Measurment\"\r\nFROM LatencyTestResults, LatencyTestMeasurments, LatencyTestParameters   \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = ${Test_Id:singlequote}\r\nAND LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}\r\nAND LatencyTestResults.Id = ${Test_Id:singlequote}\r\nAND LatencyTestMeasurments.Index < ${__to:date:ms}\r\nORDER BY LatencyTestMeasurments.SendTime"
    },
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.Index AS \"time\", \r\n  LatencyTestMeasurments.CapturedLatency AS \"Latency - Hardware Capturing\",\r\n  LatencyTestMeasurments.CapturedJitter AS \"Jitter - Hardware Capturing\"\r\nFROM LatencyTestResults, LatencyTestMeasurments, LatencyTestParameters   \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = ${Test_Id:singlequote}\r\nAND LatencyTestParameters.LatencyTestResultId = ${Test_Id:singlequote}\r\nAND LatencyTestResults.Id = ${Test_Id:singlequote}\r\nAND CapturedLatency <> -1\r\nAND LatencyTestMeasurments.Index < ${__to:date:ms}\r\nORDER BY LatencyTestMeasurments.SendTime"
    }
   ]
  },
  {
   "title": "Jitter Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Latency Histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "panelId": 13 }
   ]
  },
  {
   "title": "Jitter Histogram",
   "type": "histogram",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "panelId": 13 }
   ]
  }
 ]
}