{
 "title": "Compare two latency tests",
 "time": { "from": "1970-01-01T00:00:00.001Z", "to": "1970-01-01T00:00:00.010Z" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "mysql" },
   {
    "name": "Test1_Id",
    "label": "Test 1 - Id",
    "query": "SELECT Id FROM NetworkPerformanceTest.LatencyTestResults;"
   },
   {
    "name": "Test2_Id",
    "label": "Test 2 - Id",
    "query": "SELECT Id FROM NetworkPerformanceTest.LatencyTestResults;"
   }
  ]
 },
 "panels": [
  {
   "title": "Test 1",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Test Details",
     "type": "text",
     "gridPos": { "h": 1, "w": 14, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Message Statistics",
     "type": "text",
     "gridPos": { "h": 1, "w": 10, "x": 14, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Id",
     "type": "stat",
     "gridPos": { "h": 2, "w": 1, "x": 0, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  LatencyTestResults.Id\nFROM LatencyTestResults, LatencyTestMeasurments, LatencyTestParameters   \nWHERE LatencyTestMeasurments.LatencyTestResultId = LatencyTestResults.Id \nAND LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id \nAND LatencyTestResults.Id  = ${Test1_Id:singlequote}\nGROUP BY LatencyTestResults.Id"
      }
     ]
    },
    {
     "title": "Technology",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 1, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.TransmissionTechnology\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Protocol",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 3, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.Protocol\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Test Tool",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 5, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.TestTool\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Test Mode",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.TestMode\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Test Duration",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.TestDuration\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Target Host",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 12, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.TestServer\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Message Rate",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 14, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "msg/s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.MessagesPerSecond\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Message Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.MessageSize\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Send Messages",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  SentMessages\nFROM LatencyTestResults\nWHERE Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Received Messages",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ReceivedMessages\nFROM LatencyTestResults\nWHERE Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Lost Messages",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 2 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  LostMessages\nFROM LatencyTestResults\nWHERE Id = ${Test1_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Comment",
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.Comment\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test1_Id:singlequote}"
      }
     ]
    }
   ]
  },
  {
   "title": "Test 2",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Test Details",
     "type": "text",
     "gridPos": { "h": 1, "w": 14, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Message Statistics",
     "type": "text",
     "gridPos": { "h": 1, "w": 10, "x": 14, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
      }
     ]
    },
    {
     "title": "Id",
     "type": "stat",
     "gridPos": { "h": 2, "w": 1, "x": 0, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  LatencyTestResults.Id\nFROM LatencyTestResults, LatencyTestMeasurments, LatencyTestParameters   \nWHERE LatencyTestMeasurments.LatencyTestResultId = LatencyTestResults.Id \nAND LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id \nAND LatencyTestResults.Id  = ${Test2_Id:singlequote}\nGROUP BY LatencyTestResults.Id"
      }
     ]
    },
    {
     "title": "Technology",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 1, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.TransmissionTechnology\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Protocol",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 3, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.Protocol\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Test Tool",
     "type": "stat",
     "gridPos": { "h": 2, "w": 3, "x": 5, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.TestTool\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Test Mode",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 8, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.TestMode\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Test Duration [s]",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 10, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.TestDuration\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Target Host",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 12, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.TestServer\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Message Rate",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 14, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "msg/s" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.MessagesPerSecond\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Message Size",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.MessageSize\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Send Messages",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 18, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  SentMessages\nFROM LatencyTestResults\nWHERE Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Received Messages",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 20, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  ReceivedMessages\nFROM LatencyTestResults\nWHERE Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Lost Messages",
     "type": "stat",
     "gridPos": { "h": 2, "w": 2, "x": 22, "y": 3 },
     "options": { "reduceOptions": { "calcs": [ "max" ] } },
     "targets": [
      {
       "rawSql": "SELECT\n  LostMessages\nFROM LatencyTestResults\nWHERE Id = ${Test2_Id:singlequote}"
      }
     ]
    },
    {
     "title": "Comment",
     "type": "stat",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 5 },
     "options": { "reduceOptions": { "calcs": [ "last" ] } },
     "targets": [
      {
       "rawSql": "SELECT \r\n  LatencyTestParameters.Comment\r\nFROM LatencyTestParameters, LatencyTestResults\r\nWHERE LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id\r\nAND LatencyTestResults.Id = ${Test2_Id:singlequote}"
      }
     ]
    }
   ]
  },
  { "title": "Compare", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "Latency",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Jitter",
   "type": "text",
   "gridPos": { "h": 1, "w": 12, "x": 12, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\n  UNIX_TIMESTAMP(<time_column>) as time_sec,\n  <value column> as value,\n  <series name column> as metric\nFROM <table name>\nWHERE $__timeFilter(time_column)\nORDER BY <time_column> ASC\n"
    }
   ]
  },
  {
   "title": "Minimum",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MinimumLatency as \"Test 1 (Id: ${Test1_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id}"
    },
    {
     "rawSql": "SELECT\n  MinimumLatency as \"Test 2 (Id: ${Test2_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Average",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AverageLatency as \"Test 1 (Id: ${Test1_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id}"
    },
    {
     "rawSql": "SELECT\n  AverageLatency as \"Test 2 (Id: ${Test2_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MaximumLatency as \"Test 1 (Id: ${Test1_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id}"
    },
    {
     "rawSql": "SELECT\n  MaximumLatency as \"Test 2 (Id: ${Test2_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Standard Deviation",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  StandardDeviationLatency as \"Test 1 (Id: ${Test1_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id}"
    },
    {
     "rawSql": "SELECT\n  StandardDeviationLatency as \"Test 2 (Id: ${Test2_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Minimum",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MinimumJitter as \"Test 1 (Id: ${Test1_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id}"
    },
    {
     "rawSql": "SELECT\n  MinimumJitter as \"Test 2 (Id: ${Test2_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Average",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AverageJitter as \"Test 1 (Id: ${Test1_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id}"
    },
    {
     "rawSql": "SELECT\n  AverageJitter as \"Test 2 (Id: ${Test2_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Maximum",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MaximumJitter as \"Test 1 (Id: ${Test1_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id}"
    },
    {
     "rawSql": "SELECT\n  MaximumJitter as \"Test 2 (Id: ${Test2_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Standard Deviation",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "delta" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  StandardDeviationJitter as \"Test 1 (Id: ${Test1_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id}"
    },
    {
     "rawSql": "SELECT\n  StandardDeviationJitter as \"Test 2 (Id: ${Test2_Id})\" \nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MinimumLatency as \"Diff\"\nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id} OR LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AverageLatency as \"Diff\"\nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id} OR LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MaximumLatency as \"Diff\"\nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id} OR LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  StandardDeviationLatency as \"Diff\"\nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id} OR LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MinimumJitter as \"Diff\"\nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id} OR LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 15, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  AverageJitter as \"Diff\"\nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id} OR LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  MaximumJitter as \"Diff\"\nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id} OR LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Difference",
   "type": "stat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  StandardDeviationJitter as \"Diff\"\nFROM LatencyTestResults\nWHERE LatencyTestResults.Id = ${Test1_Id} OR LatencyTestResults.Id = ${Test2_Id}"
    }
   ]
  },
  {
   "title": "Latency Values",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.SendTime * 1000000 AS \"time\", \r\n  LatencyTestMeasurments.Latency AS \"Test 1\"\r\nFROM LatencyTestMeasurments   \r\nWHERE LatencyTestResultId = ${Test1_Id:singlequote}\r\nORDER BY SendTime"
    },
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.SendTime * 1000000 AS \"time\", \r\n  LatencyTestMeasurments.Latency AS \"Test 2\"\r\nFROM LatencyTestMeasurments   \r\nWHERE LatencyTestResultId = ${Test2_Id:singlequote}\r\nORDER BY SendTime"
    }
   ]
  },
  {
   "title": "Jitter Values",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.SendTime * 1000000 AS \"time\", \r\n  LatencyTestMeasurments.Jitter AS \"Test 1\"\r\nFROM LatencyTestMeasurments\r\nWHERE LatencyTestResultId = ${Test1_Id:singlequote}\r\nORDER BY SendTime"
    },
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.SendTime * 1000000 AS \"time\", \r\n  LatencyTestMeasurments.Jitter AS \"Test 2\"\r\nFROM LatencyTestMeasurments\r\nWHERE LatencyTestResultId = ${Test2_Id:singlequote}\r\nORDER BY SendTime"
    }
   ]
  },
  {
   "title": "Latency Histogram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.SendTime * 1000000 AS \"time\", \r\n  LatencyTestMeasurments.Latency * 1000 as \"Test 1\"\r\nFROM LatencyTestResults, LatencyTestMeasurments, LatencyTestParameters   \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = LatencyTestResults.Id \r\nAND LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id \r\nAND LatencyTestResults.Id  = ${Test1_Id:singlequote}\r\nORDER BY LatencyTestMeasurments.SendTime"
    },
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.SendTime * 1000000 AS \"time\", \r\n  LatencyTestMeasurments.Latency * 1000 as \"Test 2\"\r\nFROM LatencyTestResults, LatencyTestMeasurments, LatencyTestParameters   \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = LatencyTestResults.Id \r\nAND LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id \r\nAND LatencyTestResults.Id  = ${Test2_Id:singlequote}\r\nORDER BY LatencyTestMeasurments.SendTime"
    }
   ]
  },
  {
   "title": "Jitter Histogram",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.SendTime * 1000000 AS \"time\", \r\n  LatencyTestMeasurments.Jitter * 1000  AS \"Test 1\"\r\nFROM LatencyTestResults, LatencyTestMeasurments, LatencyTestParameters   \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = LatencyTestResults.Id \r\nAND LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id \r\nAND LatencyTestResults.Id  = ${Test1_Id:singlequote}\r\nORDER BY LatencyTestMeasurments.SendTime"
    },
    {
     "rawSql": "SELECT \r\n  LatencyTestMeasurments.SendTime * 1000000 AS \"time\", \r\n  LatencyTestMeasurments.Jitter * 1000 AS \"Test 2\"\r\nFROM LatencyTestResults, LatencyTestMeasurments, LatencyTestParameters   \r\nWHERE LatencyTestMeasurments.LatencyTestResultId = LatencyTestResults.Id \r\nAND LatencyTestParameters.LatencyTestResultId = LatencyTestResults.Id \r\nAND LatencyTestResults.Id  = ${Test2_Id:singlequote}\r\nORDER BY LatencyTestMeasurments.SendTime"
    }
   ]
  }
 ]
}