version: '3'

services:

  grafana:
    image: grafana/grafana:8.1.2
    restart: always
    ports:
      - 3000:3000
    volumes:
      - grafana-data:/var/lib/grafana grafana/grafana

  database:
    image: mariadb:10.5
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  grafana-data:
  mysql-data:
